---
- name: Run role
  hosts: all
  any_errors_fatal: true
  roles:
    - ansible-cortex
  vars:
    cortex_config_dir: /cortex
    cortex_db_dir: /cortexdb
    cortex_system_user: "vortex"
    cortex_system_group: "vortex"
    cortex_all_in_one: false
    cortex_services:
      ingester:
        server:
          http_listen_port: 9009
        ingester:
          lifecycler:
            join_after: 0
            min_ready_duration: 0s
            final_sleep: 0s
            num_tokens: 512
            ring:
              kvstore:
                store: inmemory
        storage:
          engine: blocks
        blocks_storage:
          backend: filesystem
          filesystem:
            dir: /tmp/blocks
      readpath:
        target: querier,store-gateway
        server:
          http_listen_port: 9010
          grpc_listen_port: 9096
        storage:
          engine: blocks
        querier:
          store_gateway_addresses: 127.0.0.1:9096
        blocks_storage:
          backend: filesystem
          filesystem:
            dir: /tmp/blocks
    cortex_env_variables:
      ingester:
        JAEGER_AGENT_HOST: localhost
        JAEGER_SAMPLER_PARAM: 0
        JAEGER_SAMPLER_TYPE: const
