---
- name: Copy the cortex systemd service file
  template:
    src: cortex.service.j2
    dest: /etc/systemd/system/cortex.service
    owner: root
    group: root
    mode: 0644
  notify: restart cortex

- name: configure cortex
  template:
    src: "{{ cortex_config_file }}"
    dest: "{{ cortex_config_dir }}/cortex.yml"
    force: true
    owner: root
    group: cortex
    mode: 0640
  notify:
    - reload cortex
