---
- name: Run role
  hosts: all
  any_errors_fatal: true
  roles:
    - ansible-cortex
  vars:
    cortex_config_dir: /cortex
    cortex_db_dir: /cortexdb
    cortex_system_user: "vortex"
    cortex_system_group: "vortex"
    cortex_env_variables:
      KAEGER_AGENT_HOST: localhost
      KAEGER_SAMPLER_PARAM: 0
      KAEGER_SAMPLER_TYPE: const
